apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: csi-driver-nfs
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
    - name: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
    - name: registry.k8s.io/sig-storage/csi-resizer:v1.13.1
    - name: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
    - name: registry.k8s.io/sig-storage/livenessprobe:v2.15.0
    - name: registry.k8s.io/sig-storage/nfsplugin:v4.10.0